### ISSUE TITLE
Find a way to retrieve `period_id` or subtitute for timeliness calculation reliably

### ISSUE THREAD

**Issue by georgiana-b** [gvidon/uk-expenditure#20]
Currently `period_id` is [extracted from the title/url by the `period.py` script ](https://github.com/okfn/data-quality-uk-25k-spend/blob/master/scripts/period.py#L13). This can go wrong [if the title has typos](https://github.com/okfn/data-quality-uk-25k-spend/blob/master/scripts/period.py#L257) or if it doesn't contain all the necessary information (`https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/519924/_25K_March_Data.csv`) leading to empty or wrong `period_id` and errors in `data-quality-cli` performance calculation.
The need for `period.py` script is explained by the lack of `created` or `last_modified` fields for some resources. Ex from the CKAN API response:

``` py
[{'description': 'GTCE Spend April 2011 to January 2012',
  'format': 'CSV',
  'id': '0cdc2222-867c-4586-a5b4-6022a71b3cb6',
  'position': 0,
  'revision_id': '6773cab6-21b8-47c5-a02c-d5c71f23a151',
  'tracking_summary': {'recent': 0, 'total': 0},
  'url': 'http://media.education.gov.uk/assets/files/xls/gtce%20spend%20april%202011%20to%20january%202012.csv'},
 {'description': 'QCDA April 2010',
  'format': 'CSV',
  'id': 'f748cb1d-6e1b-4620-b996-3451ebfc9702',
  'position': 0,
  'revision_id': '6773cab6-21b8-47c5-a02c-d5c71f23a151',
  'tracking_summary': {'recent': 0, 'total': 0},
  'url': 'http://media.education.gov.uk/assets/files/xsl/qcda%20spend%20%20april%202010.csv'}]

```

Proposed solutions:
1. Ensure that `data-quality-cli` and (possibly) `data-quality-dashboard` are able to deal with empty periods. 
   - Pros:
     Tools will be more error-proof which is welcomed for the [new CKAN generator feature](https://github.com/okfn/data-quality-cli/pull/12).
     - Cons:
       According to the current implementation, each [entity in the dashboard](http://uk-25k.datadashboards.io/publishers/department-for-culture-media-and-sport) will have another row with an empty `Period`.
2. Use both `period_id` and  `created` fields and [improve the scoring algorithm](https://github.com/okfn/data-quality-cli/issues/5) to not score timeliness when any one these fields is unknown. This also makes sense since by using the period extracted from the title, `period_id` no longer refers to the time of upload but time covered by the data. As I understand timeliness, being on time would mean that the month of upload is ~=month covered by the data +1. So both period of creation and period covered by data should be known. This is closely related to okfn/data-quality-cli#13
   For example, the following would be cataloged as not timely: 

```
data,format,period_id,created_at
http://data.defra.gov.uk/ops/procurement/1204/EA-OVER-25K-1204.csv,csv,2012-04-01,2013-02-07T10:18:08.619710
```

I'll drop some numbers: 
Currently we have 1306 sources which is only a subset of UK CKAN.

By using this retrieval method: 

``` py
datafile['created_at'] = resource.get('created') or ast.literal_eval(resource.get('archiver',"{}")).get('created', '')
```

From 1306  resources, 374 rows have  `created` field null.
`revision_id` field is present in all of them which could be used to get the time of last update on CKAN. This however doesn't solve the problem if the concept of timeliness is what I explained above. 

There is only 1 field where `period_id` is null which is insignificant in the context of this app, but I think the above mentioned issues provide some important insights into how to make data-quality-cli/dashboard better.

**Comment by pwalsh** [comment]
@georgiana-b 

( cc @akariv @amercader @jobarratt )

I've been thinking about timeliness, and how we can "score" it, and the related challenges.
- For timeliness, the datetime in `created` (from CKAN resources) is our best  indicator of **actual publication date**.
- Timeliness refers to the gap between when a dataset _should_ have been published, and when it was published
- When something _should_ have been published is hard to assess. Generally, we are referring to this as the "period" of the data (the period the data is relevant for)
- I see the following possibilities for knowing when a dataset "should have been" published, and each could be implemented as a different strategy for detecting the data period:
  - [ ] it is explicitly declared as a date/datetime on some object property ( easy, but does not reflect our current data )
  - [ ] it can be extracted from some object property ( parse string and throw relevant parts at the `dateutil` parser http://dateutil.readthedocs.io/en/stable/parser.html )
  - [ ] it can be extracted from the name of the resource file ( parse file name and throw relevant parts at the `dateutil` parser http://dateutil.readthedocs.io/en/stable/parser.html  - this is what we do right now for the UK 25k spend data)

Following, if none of the above strategies can be applied to a set of data in order to consistently build knowledge about the period the data belongs to, and the actual date the data was published, then, we cannot include "timeliness" as part of the scoring in such cases ( https://github.com/okfn/data-quality-cli/issues/13 ).

@georgiana-b for the case you outline above in solution 1. The case here is:
- we are measuring timeliness
- we use a "parse filename to extract period" strategy
- we have some cases (how many, exactly) where we cannot detect a period from the filename

So, in those cases, and those cases only, I think we should use `created` date as the period, thereby giving "benefit of the doubt" to the publishing body that the data is published in a timely manner. The caveat here is, if we are not detecting a period in more than, say, 10% of cases, we should really re-consider why timeliness is scored at all.

Thoughts?

@georgiana-b can you tell us, with the UK spend data, exactly how many cases we have where period _cannot_ be extracted for a given data source?

**Comment by georgiana-b** [comment]
> @georgiana-b can you tell us, with the UK spend data, exactly how many cases we have where period cannot be extracted for a given data source

Currently, 1 source.

**Comment by pwalsh** [comment]
@georgiana-b excellent. So fallback to `created`, so that one also has a date.

**Comment by pwalsh** [comment]
Closing in favor of https://github.com/frictionlessdata/data-quality-cli/issues/13 as this is a general issue with calculating timeliness
